### PR TITLE
Add 2-5

### PR DESCRIPTION
**Pull request by Kuhaku9893**
Add 2-5

### CODE REVIEW

**Review by xumingkuan — APPROVED** [review]
Thanks for your contribution! I've just tried this level and it was interesting. Similar to the levels 2-1 to 2-4, yet different.

**Comment by Kuhaku9893** [comment]
I am glad you appreciate it.

I am also making custom stages and releasing them on my blog.
I was happy to know that there are others who have released custom stages besides myself, so I thought of a stage based on 2-1 to 2-4.

Thank you very much.

**Comment by xumingkuan** [comment]
By the way, I'm gradually posting the solutions for my custom stages on Bilibili (the Chinese YouTube). Here's the video for Stage 1-1: https://www.bilibili.com/video/BV1gH4y1w7RT/

Is it OK if I also post the solutions to the stages on your blog if I manage to solve them in the future? I will make sure to mention your blog in the video description.

Also, how did you get the non-R18 version of the game? I saw on your blog that you're using version 1.02 of the game but I've only downloaded version 1.01. Does version 1.02 provide an option to turn off the R18 patch?

Thanks in advance.

**Comment by Kuhaku9893** [comment]
No problem, You may post my custom stage solutions.

Please check the sales page for the all ages version.

**Comment by xumingkuan** [comment]
Got it, thanks!

**Pull request merged**
